
version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
        depends_on:
            - ws1
            - ws2
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:80
    ws1:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - rds
            - mongo
        environment:
            - APPID=WS_1
    ws2:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - rds
            - mongo
        environment:
            - APPID=WS_2
    rds:
        image: redis
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
